[package]
name = "super_sdg"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
rand = { version = "0.8.5" }
bevy_editor_pls = "0.8.1"
bevy-fps-counter = "0.4.0"

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# LTO (Link-Time-Optimization)
[profile.release]
lto = "thin"
